### ISSUE TITLE
LuaZ80 fails executing

### ISSUE THREAD

**Issue by SiENcE** [robzed/LuaZ80#1]
Hey,

I think commit 1b94fc1bed3789febe01fa9981944f1e8370a2a0 is wrong as the next_pc parameter is not used.

ZXSPectrum fails executing.
lua52: lua_z80.lua:306: bad argument #6 to 'format' (number expected, got ni

stack traceback:
    [C]: in function 'format'
    lua_z80.lua:306: in function 'write_2bytes_to_address_command_string'
    lua_z80.lua:414: in function 'instruction'
    lua_z80.lua:932: in function 'decode_instruction'
    lua_z80.lua:967: in function 'z80_compile'
    lua_z80.lua:1217: in function 'run_z80'
    .\z80_ss_debug.lua:464: in function 'run_z80'
    test_fake_ZXSpectrum.lua:54: in function 'run_Spectrum'
    test_fake_ZXSpectrum.lua:67: in main chunk
    [C]: in ?

cheers

**Comment by robzed** [comment]
Thanks for the report - I'll take a look over the next few days and report back.

**Comment by robzed** [comment]
Simple error with parameter inside wrong parentheses:
    string.format("memory[0x%x]", addr+1, iaddr)), iaddr
should be:
    string.format("memory[0x%x]", addr+1), iaddr), iaddr

See 945ed963a032add255ade963de54948da22f176c

Sadly, there are other issues when translating the ZX Spectrum ROM, which I'll have to work on.
